//BUTTONS
export const btnEnviar = document.getElementById('enviar')
export const btnCopiar = document.getElementById('copiar')
export const btnRedes = document.getElementById('share')
export const reddit = document.getElementById('reddit')
export const twitter = document.getElementById('twitter')
export const whatsapp = document.getElementById('whatsapp')
export const btnQRCode = document.getElementById('qr-code')
export const downloadQR = document.getElementById('downloadQR')
export const btnOpt = document.getElementById('opt')
export const btnSalvar = document.getElementById('salvar')
export const btnDeletar = document.getElementById('btnDeletar')
export const btnNaoDeletar = document.getElementById('btnNaoDeletar')

//INPUTS
export const inputUrl = document.getElementById('input-url')
export const inputPath = document.getElementById('inputPath')
export const inputURLModal = document.getElementById('inputURLModal')
//FIELDS
export const campoResultado = document.getElementById('container-link')
export const linkEncurtado = document.getElementById('link')
export const containerBtnCompartilhar = document.getElementById('container-btn')
export const sucessoCopiar = document.getElementById('sucesso-copiar')
export const redesSociais = document.getElementById('redesSociais')
export const imgQRCode = document.getElementById('QRcode')
export const encurtamento = document.getElementById('encurtamento')
export const gerenciamento = document.getElementById('gerenciamento')
export const tabelaLinks = document.getElementById('resultadoTabela')
export const dominio = document.getElementById('dominio')
export const editar = document.getElementById('editar')
export const blurClick = document.querySelectorAll('.blur')
export const deletarModal = document.getElementById('deletar')